#!/bin/bash

#COLORS
RESTORE='\033[0m'

RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'
BLUE='\033[00;34m'
PURPLE='\033[00;35m'
CYAN='\033[00;36m'
LIGHTGRAY='\033[00;37m'

LRED='\033[01;31m'
LGREEN='\033[01;32m'
LYELLOW='\033[01;33m'
LBLUE='\033[01;34m'
LPURPLE='\033[01;35m'
LCYAN='\033[01;36m'
WHITE='\033[01;37m'

UL='\033[4m'    # underline







#Menu Nmap
menu_nmap(){
echo -e "${LRED}(1)${RESTORE} Nmap classique"
echo -e "${LRED}(2)${RESTORE} Nmap avec OS"
echo -e "\n${LRED}(3)${RESTORE} Retour Menu\n\n"

read -p $"Choisisssez une option:" option

if [[ $option == 1 ]]
        then
		read -p $"quelle adresse IP ? :" IP
		nmap $IP
		sleep 5
		menu
elif [[ $option == 2 ]]
        then
		read -p $"quelle adresse IP ? :" IP
		nmap -v -O -T4 -Pn -oG OSDetect  $IP
		sleep 5
		menu
elif [[ $option == 3 ]]
        then
                menu


else
        echo "vous n'avez pas choisi une option valable"
        scan
fi
}

#Menu Principal
menu_main(){
clear
banner
echo -e "Vous travaillez actuellement sur le projet ${LBLUE}$name_projet${RESTORE}\n"
echo -e "Menu principal et actions possibles dans le ${LRED}RedBook${RESTORE}\n"
echo -e "${LRED}(1)${RESTORE} Nmap"
echo -e "\n${LRED}(Q)${RESTORE} Quitter\n\n"

read -p $"Choisisssez une option:" option

if [[ $option == 1 ]]; then
	menu_nmap
elif [[ $option == Q || $option == q ]]; then
	exit 1
else
	echo "vous n'avez pas choisi une option valable"
	menu_main
fi
}

#MENU Dossier
menu_start(){

if [[ ! -d Projets ]]; then
	mkdir Projets
else
	i="2"
fi

echo -e "${LRED}(1)${RESTORE} Créer un nouveau projet"
echo -e "${LRED}(2)${RESTORE} Reprendre un projet en cours"
echo -e "\n${LRED}(Q)${RESTORE} Quitter\n\n"

read -p "Choisissez une option :" option

if [[ $option == 1 ]]; then
	read -p $"Nom du nouveau projet :" name_projet
	projet="Projets/"$name_projet
	while [[ -d $projet ]]; do
		echo -e "Le projet ${LBLUE}$name_projet${RESTORE} existe déjà.\n"
		read -p $"Nom du nouveau projet :" name_projet
		projet="Projets/"$name_projet
	done
	mkdir $projet
	menu_main

elif [[ $option == 2 ]]; then
	echo -e "\n${UL}Voici les projets en cours${RESTORE}\n"
	ls Projets
	echo -e "\n"
	read -p $"Nom du projet à continuer :" name_projet
	projet="Projets/"$name_projet
	while [[ ! -d $projet ]]; do
		echo -e "Le projet ${LBLUE}$name_projet${RESTORE} n'existe pas.\n"
		read -p $"Nom du projet à continuer :" name_projet
		projet="Projets/"$name_projet
	done
	menu_main

elif [[ $option == Q || $option == q ]]; then
	exit 1

else
	echo -e "\nVous n'avez pas choisi une option valable"
	sleep 5
	clear
	banner
	menu_start
fi
}

#BANNER
banner(){
echo -e "${LRED}
\t    ____________________   ___________________    
\t.-/|                    \ /                   |\-.
\t||||                     |                    ||||
\t||||  ____          _ ____              _     ||||
\t|||| |  _ \ ___  __| | __ )  ___   ___ | | __ ||||
\t|||| | |_) / _ \/ _\ |  _ \ / _ \ / _ \| |/ / ||||
\t|||| |  _ <  __/ (_| | |_) | (_) | (_) |   <  ||||
\t|||| |_| \_\___|\__,_|____/ \___/ \___/|_|\_\ ||||
\t||||                     |                    ||||
\t||||                     |                    ||||
\t||||                     |                    ||||
\t||||                     |                    ||||
\t||||                     |          benoit.g  ||||
\t||||                     |           cyril.d  ||||
\t||||____  ______________ | __________________ ||||
\t||/=====================\|/====================\||
\t'----------------------~___~--------------------''
${RESTORE}\n\t\tBonjour et bienvenue dans le ${LRED}RedBook${RESTORE}\n"
echo -e "Le ${LRED}RedBook${RESTORE} à été créé pour un usage éthique dans le cadre de tests d'intrusion"
echo -e "Le ${LRED}Redbook${RESTORE} ne doit en aucun cas être utilisé afin de nuire à toute personne physique ou morale\n\n\n"
}

#START
clear
banner
menu_start
